### ISSUE TITLE
Does not work in fragile frames within beamer document class

### ISSUE THREAD

**Issue by mrbela** [markroyer/latex-listings-eclipse#1]
The package lstcustom causes problems if it used in a fragile frame in beamer document classes.

More information can seen [https://tex.stackexchange.com/questions/586477/missing-number-treated-as-zero-within-beamer-and-lstcustom](https://tex.stackexchange.com/questions/586477/missing-number-treated-as-zero-within-beamer-and-lstcustom).

Anyway, great work. Thanks a lot!

**Comment by markroyer** [comment]
Thanks for pointing out the problem and providing a solution! I've updated the project to work with fragile Beamer slides, and I've added a working beamer example using inline, block, and include listing options.
